### ISSUE TITLE
About performance?

### ISSUE THREAD

**Issue by YamamotoSayaka** [j3xugit/RaptorX-Contact#1]
Hi, I'm also implementing Xu's paper for protein contact prediction.
However, my performance is much worse from the original paper, around 20 points less on casp11.
Can you kindly share your performance? 

Many thanks!

**Comment by j3xugit** [comment]
Please check out our performance in the paper at https://journals.plos.org/ploscompbiol/article/metrics?id=10.1371/journal.pcbi.1005324 .
You may download 3 test datasets at http://raptorx.uchicago.edu/download/ . Once you login to this download web page, please check out instructions in 0README.data4contactPrediction.txt for dataset description.
